---

- hosts: all
  become: true
  pre-tasks:

  - name: install updates(CentOS)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates(Debian)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Debian"



# The following executes only in web_servers section
# from the inventory
- hosts: web_servers
  become: true
  tasks:

###Debian
  - name: Install Debian apache2 and php packages
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Debian"
    # when: ansible_distribution in ["Ubuntu", "Debian", "Kali", "Raspbian"]



### Centos
  - name: Install CentOS apache2 and php packages
    dnf:
      name: 
      - httpd
      - php
      state: latest
    when: ansible_distribution == "CentOS"
    