---
- hosts: all
  become: true
  tasks:

    ## Debian and its derivatives
    - name: Update cache and install Debian apache2 & php packages
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
        update_cache : yes
      when: ansible_distribution == "Debian"

    ### CentOS and its derivatives
    - name: Update cache and install CentOS apache2 & php packages
      dnf:
        name:
          - httpd
          - php
        state: latest
        update_cache: yes
      when: ansible_distribution == "CentOS"

