---

- hosts: all
  become: true
  tasks:

  - name: Update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Debian"
      # when: ansible_distribution in ["Ubuntu", "Debian", "Kali", "Raspbian"]

  - name: Install apache2 package
    apt:
      name: apache2
    when: ansible_distribution == "Debian"
    # when: ansible_distribution in ["Ubuntu", "Debian", "Kali", "Raspbian"]

  - name: Install php support for Apache2
    apt:
      name: libapache2-mod-php
    when: ansible_distribution == "Debian"
        #when: ansible_distribution in ["Ubuntu", "Debian", "Kali", "Raspbian"]    
